# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HubstaffTui < Formula
  desc "Fast Hubstaff time tracking TUI for tmux floating popups"
  homepage "https://github.com/Nathan-ma/hubstaff-tui"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nathan-ma/hubstaff-tui/releases/download/v1.0.0/hubstaff-tui_1.0.0_darwin_amd64.tar.gz"
      sha256 "7205d7e8e0fda5d72e80f2053aa76aa035847b757f8d2210f775701f02f23f6a"

      define_method(:install) do
        bin.install "hubstaff-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nathan-ma/hubstaff-tui/releases/download/v1.0.0/hubstaff-tui_1.0.0_darwin_arm64.tar.gz"
      sha256 "949f3c9a662374803745f5eb82983d831b7581cfc4d8c426d2ca1c1b2d01bdcb"

      define_method(:install) do
        bin.install "hubstaff-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nathan-ma/hubstaff-tui/releases/download/v1.0.0/hubstaff-tui_1.0.0_linux_amd64.tar.gz"
      sha256 "65d476e61dabe51425b404130e5ccc37bc6632a2ec0cac8ac4f25348c4f8e368"
      define_method(:install) do
        bin.install "hubstaff-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nathan-ma/hubstaff-tui/releases/download/v1.0.0/hubstaff-tui_1.0.0_linux_arm64.tar.gz"
      sha256 "8cbcddcfd5caac4dba4da4cdde0f743eac8c80acb390d9c4192324a9bea87c8f"
      define_method(:install) do
        bin.install "hubstaff-tui"
      end
    end
  end
end
