# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HubstaffTui < Formula
  desc "Fast Hubstaff time tracking TUI for tmux floating popups"
  homepage "https://github.com/Nathan-ma/hubstaff-tui"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nathan-ma/hubstaff-tui/releases/download/v0.1.0/hubstaff-tui_0.1.0_darwin_amd64.tar.gz"
      sha256 "2d284f549a064d3d1324d7b78774206ac182639461e8660989140d883b8de441"

      define_method(:install) do
        bin.install "hubstaff-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nathan-ma/hubstaff-tui/releases/download/v0.1.0/hubstaff-tui_0.1.0_darwin_arm64.tar.gz"
      sha256 "59effd2f2251e029e67c47282b07719181a0928e5bf104969f631f448a910352"

      define_method(:install) do
        bin.install "hubstaff-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nathan-ma/hubstaff-tui/releases/download/v0.1.0/hubstaff-tui_0.1.0_linux_amd64.tar.gz"
      sha256 "13f0436531bea64e3e3e29c1a55417fc777951c05322628211ab9a211f081c59"
      define_method(:install) do
        bin.install "hubstaff-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nathan-ma/hubstaff-tui/releases/download/v0.1.0/hubstaff-tui_0.1.0_linux_arm64.tar.gz"
      sha256 "8761ac8b255edb01c7719da8b57d7ae8041102ba829e1f1239d1936e143f0857"
      define_method(:install) do
        bin.install "hubstaff-tui"
      end
    end
  end
end
