# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HubstaffTui < Formula
  desc "Fast Hubstaff time tracking TUI for tmux floating popups"
  homepage "https://github.com/Nathan-ma/hubstaff-tui"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nathan-ma/hubstaff-tui/releases/download/v0.2.0/hubstaff-tui_0.2.0_darwin_amd64.tar.gz"
      sha256 "293a5a2a3e069f15390b420d8699905989c341b2dc3dc6871bd98536a8382cd3"

      define_method(:install) do
        bin.install "hubstaff-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nathan-ma/hubstaff-tui/releases/download/v0.2.0/hubstaff-tui_0.2.0_darwin_arm64.tar.gz"
      sha256 "705a00b437e3f4d2b645ecd285da637bc2914694bceec70748bc1e11b7f3ed36"

      define_method(:install) do
        bin.install "hubstaff-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nathan-ma/hubstaff-tui/releases/download/v0.2.0/hubstaff-tui_0.2.0_linux_amd64.tar.gz"
      sha256 "5c7e154c60f395bd91882229ae133484336b81c150289a58f2665bd3a291beab"
      define_method(:install) do
        bin.install "hubstaff-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nathan-ma/hubstaff-tui/releases/download/v0.2.0/hubstaff-tui_0.2.0_linux_arm64.tar.gz"
      sha256 "68b3f1199f9fd4faa652db0abf12d73d107ee203edd58c32f8b24819dcf44004"
      define_method(:install) do
        bin.install "hubstaff-tui"
      end
    end
  end
end
